### ISSUE TITLE
game crash upon attempting to load TOP recordings

### ISSUE THREAD

**Issue by princessoak** [UnknownX7/ARealmRecorded#31] opened 2024-09-28 05:58 UTC
When I try to load any of my recordings from TOP, my game instantly crashes. I tested with zero plugins other than A Realm Recorded, and the issue persisted.

**Comment by Uragawa** [comment] 2024-09-29 07:34
Possible duplicate of #30 . Do you have an exception log? I never got around to reporting an issue and haven't checked it recently but at one point DSR would reliably cause this for me, with a crash in `FormatAddonTextTimestampDetour`.

**Comment by princessoak** [comment] 2024-09-30 05:29
Question — what do you mean exactly by exception log? I do have the log that dalamud prompts you to save when it crashes; and I also screenshot the.. call stack, or something?, from that same window that popped up.

**Comment by Uragawa** [comment] 2024-10-02 04:33
Yeah, the log showing the exception thrown, if there is one (some crashes do not leave that sort of evidence) with the call stack.

**Comment by princessoak** [comment] 2024-10-02 04:41
Okay — umm.. can I send it by email or disc or something?

**Comment by Uragawa** [comment] 2024-10-02 04:47
I was hoping for an excerpt that could be posted here, but if you have privacy concerns, I'm not associated with the project so it might be best to wait for @UnknownX7 to get on this. Until then, save the log somewhere you'll remember.

**Comment by Uragawa** [comment] 2024-11-11 06:37
@UnknownX7 I just got a crash from a TOP recording myself and it is indeed originating from the same function as my (unreported) DSR crashes.
```
Unhandled native exception occurred at kernelbase.dll+13C47
Code: C0000005
Dump at: Z:\<REDACTED>\.xlcore\logs\dalamud_appcrash_20241111_032108_411_468.dmp
System Time: 2024-11-11 06:21:30.8008247

   at ARealmRecorded.Game.FormatAddonTextTimestampDetour(IntPtr raptureTextModule, UInt32 addonSheetRow, Int32 a3, UInt32 hours, UInt32 minutes, UInt32 seconds, UInt32 a7)

   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework)
```

**Comment by ffritsche** [comment] 2024-11-30 17:10
Same here for FRU. There seems to be a pull request for this error.

**Closed** 2024-12-01 19:56 UTC
